### ISSUE TITLE
[FEATURE] 1:1 채팅 디벨롭/ 전체 채팅 조회 API

### ISSUE THREAD

**Issue by yj-leez** [Team-ATCH/ATCH-Server#7]
## Description
1:1 채팅 시 채팅 방에 존재하는 유저인지 확인하는 기능을 추가하고, 누구나 전체 채팅을 조회할 수 있는 기능을 구현합니다.
## Todo
- [x] 채팅 송신 시 사용자가 채팅방에 존재하는지 확인
- [x] 전체 채팅 조회 기능
- [x] 전체 채팅 조회 시 페이지네이션 적용
## ETC
전체 채팅 조회 기능은 '모든 채팅방과 각 채팅방의 첫 번째 채팅만 조회' 기능을 뜻합니다.
